### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by thesauri** [thesauri/korsord#17]
Currently, drawing listens to mouse events. Drawing should be updated to support touch events properly. Some thought needs to be put into how to differentiate between panning and drawing.

**Comment by thesauri** [comment]
* Support writing with a pen
* Touching with one finger should draw
* Two fingers should pan

**Comment by Pingviinituutti** [comment]
Pinching should zoom in and vice versa

**Comment by thesauri** [comment]
Panning and zooming currently work, but drawing is not. If touch events are captured for drawing there are two options:

1. Panning occurs simultaneously while drawing (annoying), or
2. No panning occurs when drawing (done by calling `event.preventDefault()` on touch events)

The second option is desirable. This, however, requires "reimplementing" support for panning and zooming by making sure `event.preventDefault()` is not called when two fingers or more are present. I attempted to this in #34, I'd appreciate a double check to verify that it behaves as expected.
