### ISSUE TITLE
Help panel in the game view

### ISSUE THREAD

**Issue by thesauri** [thesauri/korsord#18]
Add a panel to the game view with instructions on how to change between brush and erase mode. It could also be nice to display whether the user has the brush or eraser selected. There could also be links to solve other crosswords.

**Comment by jhnj** [comment]
I would do something like (order doesn't matter):

| Home | ?  | B/E/W |
| - | - | - |

Where **Home** would be a link to the front page (solve other...), **?** would open a larger tooltip with some instructions and keys, and **B/E/W** would indicate whether brush/eraser/writing mode is selected. If we add erase with right click as an option this could also show that.

**Comment by thesauri** [comment]
Added in #27
